name: "Do Work"
description: "Do the real work."

inputs:
  arch:
    type: string
    required: true
  sources-two:
    type: string
    required: true
  log-path:
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Show some info
      run: |
        pwd
        ls -R
        ls -R ${{ inputs.sources-two }}
        cat log
    - name: Append to artifact
      run: |
        echo "Hello from action of 2" >> log
        git -C ${{ inputs.sources-two }} log | head -20 >> ../log
    - name: Archive log
      uses: actions/upload-artifact@v3
      with:
        name: log-artifact2
        path: log
