name: CI-2

on:
  pull_request:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout self
        uses: actions/checkout@v3
        with:
          path: two
      - name: Download artifact from ci1
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: c-mauderer/github-ci-1
          branch: main
          workflow: one.yml
          workflow_conclusion: success
          name: log-artifact
      - name: Run custom work action
        uses: ./two/.github/actions/work
        with:
          arch: xxx
          sources-two: two
