name: CI-2

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      use_artifact:
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: c-mauderer/github-ci-2
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: my-log
          path: path/to/artifact
      - name: Show artifact
        run: |
          pwd
          ls -R
          cat path/to/artifact/log
      - name: Append to artifact
        run: |
          echo "Hello from 2" >> log
          git log | head -20 >> log
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-log2
          path: log
