name: CI-2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        id: cache
        with:
          path: log
          key: ${{ github.sha }}-${{ runner.os }}-xxx
      - name: Download artifact from ci1
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: c-mauderer/github-ci-1
          branch: main
          workflow: one.yml
          workflow_conclusion: success
          name: log-artifact
  call_work:
    needs: build
    uses: c-mauderer/github-ci-2/.github/workflows/work.yml@main
    with:
      arch: xxx
      action-repo: ${{ github.repository }}
      cache-key: ${{ github.sha }}-${{ runner.os }}-xxx
